server:
  port: 8102
spring:
  application:
    name: spring-admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6389

  cloud:
    loadbalancer:
      retry:
        enabled: true    # enable retry for failed calls
      ribbon:
        enabled: false    # if you had Ribbon previously, disable it
    consul:
      host: 127.0.0.1
      port: 8510
      discovery:
        register: true
        service-name: spring-admin