server:
  port: 8101
spring:
  application:
    name: spring-project
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://127.0.0.1:3316/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    user: admin
    password: admin
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6389
  cloud:
    loadbalancer:
      retry:
        enabled: true    # enable retry for failed calls
      ribbon:
        enabled: false    # if you had Ribbon previously, disable it
    consul:
      host: 127.0.0.1
      port: 8510
      discovery:
        register: true
        service-name: spring-project