name: BDD Tests

on:
  workflow_run:
    workflows: ["CI Build"]   # must match the name in ci.yml
    types:
      - completed             # trigger after ci.yml completes

jobs:
  run-bdd-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact (docker tag or build number)
        uses: actions/download-artifact@v4
        with:
          name: build-info     # must match uploaded name in ci.yml

      - name: Read build number
        id: buildnum
        run: |
          BUILD_NUMBER=$(cat build-number.txt)
          echo "Build number is: $BUILD_NUMBER"
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Run BDD Tests with correct Docker image
        run: |
          echo "Running BDD against docker image with tag ${{ steps.buildnum.outputs.build_number }}"
          # Here you would: docker pull yourorg/yourimage:${{ steps.buildnum.outputs.build_number }}
          # and then: mvn verify -P bdd